### ISSUE TITLE
Update test generators to use tests.toml files

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/csharp#1426]
PR #1424 added `tests.toml` files for all exercises. We should update our test generator to only generate tests for the test cases that are in the `tests.toml` files and where the test is included (meaning its UUID is assigned `true` as its value).

The test generator should also remove the line at the top of generated test files that contains the versioning information (which is no longer present).

Depends on #1425 being done first.

**Comment by mkushnikov** [comment]
Hi @ErikSchierboom

1. I've checked the practice exercises and not all of them contains `tests.toml`(e.g. `accumulate`). Is it ok?
2. According to the PR #1509, all `.toml` files' format was changed. So now we need to check is the field `include = true` instead of `UUID`?
3. And the last one. The changes should be done for the `generate-tests.ps1` script, right? Since I don't get it from the description.

**Comment by valentin-p** [comment]
1. Some exercises do not need tests.toml because the tests are not coming from the problem-specifications repository, in that case, tests are specific to the c# track only, so they don't need any toml file and don't need to be auto-generated. (accumulate is an exercise that has been newly added to problem-specifications and the toml file should be generated by the configlet, it's an exception)
2. Exactly, and if `include = true` is missing you can assume it is true, if it's false for a test case then the test case should not be generated for that exercise.
3. The changes should probably be done in the c# files to remove the version and filter properly the tests cases for which we want the generators project to auto-generate the tests. (The Powershell file only runs the generators project) File: generators/Exercises/GeneratorExercise.cs

**Comment by mkushnikov** [comment]
I tried to run the Generator project to test my changes but got some exceptions.

```
[18:46:38 ERR] Exception occured: Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Exercism.CSharp.Input.CanonicalDataFile.UpdateToLatestVersion() in E:\Development\C#\csharp\generators\Input\CanonicalDataFile.cs:line 57
   at Exercism.CSharp.Input.CanonicalDataFile.DownloadData() in E:\Development\C#\csharp\generators\Input\CanonicalDataFile.cs:line 33
   at Exercism.CSharp.Program.RegenerateTestClasses(Options options, String[] args) in E:\Development\C#\csharp\generators\Program.cs:line 41
   at Exercism.CSharp.Program.<>c__DisplayClass0_0.<Main>b__0(Options options) in E:\Development\C#\csharp\generators\Program.cs:line 19
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Exercism.CSharp.Program.Main(String[] args) in E:\Development\C#\csharp\generators\Program.cs:line 18
```

If I commit this line in the RegenerateTestClasses method

```
 private static void RegenerateTestClasses(Options options, string[] args)
        {
            options.Setup(args);

            var canonicalDataFile = new CanonicalDataFile(options);
            // canonicalDataFile.DownloadData();   <----- this causes the first exception

            if(options.ShouldGenerate)
                Log.Information("Re-generating test classes...");
            
            var canonicalDataParser = new CanonicalDataParser(canonicalDataFile);

            foreach (var exercise in new ExerciseCollection(canonicalDataFile, options))
                RegenerateTestClass(exercise, options, canonicalDataParser);

            if (options.ShouldGenerate)
                Log.Information("Re-generated test classes.");
        }
```
then I will get the second one - it can't deserialise `track's config.json`:

```
[18:49:16 ERR] Exception occured: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'Exercism.CSharp.Input.TrackConfigFile+ConfigExercise[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'exercises.concept', line 24, position 14.
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'Exercism.CSharp.Input.TrackConfigFile+ConfigExercise[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'exercises.concept', line 24, position 14.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value)
   at Exercism.CSharp.Input.TrackConfigFile.GetExercises() in E:\Development\C#\csharp\generators\Input\TrackConfigFile.cs:line 16
   at Exercism.CSharp.Exercises.ExerciseCollection.GetExercises()+MoveNext() in E:\Development\C#\csharp\generators\Exercises\ExerciseCollection.cs:line 36
   at Exercism.CSharp.Program.RegenerateTestClasses(Options options, String[] args) in E:\Development\C#\csharp\generators\Program.cs:line 48
   at Exercism.CSharp.Program.<>c__DisplayClass0_0.<Main>b__0(Options options) in E:\Development\C#\csharp\generators\Program.cs:line 19
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Exercism.CSharp.Program.Main(String[] args) in E:\Development\C#\csharp\generators\Program.cs:line 18
```

Could you help me to realise what's wrong?

**Comment by ErikSchierboom** [comment]
> System.NullReferenceException: Object reference not set to an instance of an object.

From the stack trace, I think this has to do with the fact that prob-specs exercises (and our exercises too) used to have a version, but we don't have that anymore. Any references to versions should be removed from the code.

> Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'Exercism.CSharp.Input.TrackConfigFile+ConfigExercise[]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.

This will be because the format of the `config.json` file has changed. In this particular case, I think the issue is that practice exercises used to be defined in the `exercises` key, but are now defined in the `exercises.practice` key.

**Comment by mkushnikov** [comment]
Hi
@ErikSchierboom Thank you, I had resolved the issues, now it works.

I have a question regarding the `tests.toml` files. 
Currently, all of them placed into `\exercises\practice\{exercise_name}\.meta` folders.
But the generator uses the `problem-specifications` folder(according to the following method in `Options.cs`)
 ```
private static string DefaultCanonicalDataDirectory
            => Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData), "exercism", "problem-specifications");
```

Should the files be added to this folder? Or the generator should parse the `exercises` folder as well to check test cases?

**Comment by ErikSchierboom** [comment]
Good questions! The whole `problem-specifications` integration should be removed. The generator should just be using the `.meta/tests.toml` files to determine which test cases to include. 

Removing the `problem-specifications` code will also mean some other more minor changes, like not seeing which exercises are outdated or which exercises are not implemented. Those will all become features of configlet, so I think we can safely remove them from the code.
