### ISSUE TITLE
Calling .SetConstructorInputParameters result in run-time error in some generators

### ISSUE THREAD

**Issue by ShamilS** [exercism/csharp#566]
Calling .SetConstructorInputParameters result in run-time error "The given key was not present in the dictionary" in some of the generators. Run-time error happens not when constructor input parameters are set but on later stage of the test code generation workflow when improperly set constructor input parameters are used to render test method body.

    [20:01:06 INF] Updating repository to latest version...
    [20:01:08 INF] Updated repository to latest version.
    [20:01:08 INF] Re-generating test classes...
    [20:01:10 ERR] Exception occured: The given key was not present in the dictionary.
    System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
    at System.ThrowHelper.ThrowKeyNotFoundException()
    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
    at Generators.Input.CanonicalDataCase.<get_ConstructorInput>b__17_1(String parameter) in .\exercism\csharp\generators\Input\CanonicalDataCase.cs:line 31
    at System.Linq.Enumerable.ToDictionary[TSource, TKey, TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
    at System.Linq.Enumerable.ToDictionary[TSource, TKey, TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
    at Generators.Input.CanonicalDataCase.get_ConstructorInput() in .\exercism\csharp\generators\Input\CanonicalDataCase.cs:line 31
    at Generators.Output.TestMethodBodyData.get_ConstructorInput() in .\exercism\csharp\generators\Output\TestMethodBodyData.cs:line 34
    at Generators.Output.TestMethodBodyData.get_ConstructorParameters() in .\exercism\csharp\generators\Output\TestMethodBodyData.cs:line 24
    at Generators.Output.TestMethodBodyData.get_SutVariableDeclaration() in .\exercism\csharp\generators\Output\TestMethodBodyData.cs:line 39
    at Generators.Output.TestMethodBodyData.get_Variables() in .\exercism\csharp\generators\Output\TestMethodBodyData.cs:line 55
    at Generators.Output.TestMethodBody.InitializeTemplateParameters() in .\exercism\csharp\generators\Output\TestMethodBody.cs:line 44
    at Generators.Output.TestMethodBody..ctor(CanonicalDataCase canonicalDataCase, CanonicalData canonicalData) in .\exercism\csharp\generators\Output\TestMethodBody.cs:line 13
    at Generators.Output.TestMethodBodyWithEqualityCheck..ctor(CanonicalDataCase canonicalDataCase, CanonicalData canonicalData) in .\exercism\csharp\generators\Output\TestMethodBodyWithEqualityCheck.cs:line 8
    at Generators.GeneratorExercise.CreateTestMethodBody(CanonicalDataCase canonicalDataCase) in .\exercism\csharp\generators\GeneratorExercise.cs:line 111
    at Generators.GeneratorExercise.RenderTestMethodBody(CanonicalDataCase canonicalDataCase) in .\exercism\csharp\generators\GeneratorExercise.cs:line 86
    at Generators.GeneratorExercise.CreateTestMethod(CanonicalDataCase canonicalDataCase, Int32 index) in .\exercism\csharp\generators\GeneratorExercise.cs:line 72
    at Generators.GeneratorExercise.RenderTestMethod(CanonicalDataCase canonicalDataCase, Int32 index) in .\exercism\csharp\generators\GeneratorExercise.cs:line 70
    at System.Linq.Enumerable.<SelectIterator>d__154`2.MoveNext()
    at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
    at System.Collections.Generic.SparseArrayBuilder`1.AddRange(IEnumerable`1 items)
    at System.Collections.Generic.SparseArrayBuilder`1.ReserveOrAdd(IEnumerable`1 items)
    at System.Linq.Enumerable.Concat2Iterator`1.ToArray()
    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
    at Generators.GeneratorExercise.RenderTestMethods() in .\exercism\csharp\generators\GeneratorExercise.cs:line 60
    at Generators.GeneratorExercise.CreateTestClass() in .\exercism\csharp\generators\GeneratorExercise.cs:line 62
    at Generators.GeneratorExercise.Render() in .\exercism\csharp\generators\GeneratorExercise.cs:line 23
    at Generators.Output.ExerciseWriter.WriteToFile(GeneratorExercise generatorExercise) in .\exercism\csharp\generators\Output\ExerciseWriter.cs:line 10
    at Generators.GeneratorExercise.Regenerate(CanonicalData canonicalData) in .\exercism\csharp\generators\GeneratorExercise.cs:line 20
    at Generators.Program.RegenerateTestClass(Exercise exercise, Options options, CanonicalDataParser canonicalDataParser) in .\exercism\csharp\generators\Program.cs:line 62
    at Generators.Program.RegenerateTestClasses(Options options) in .\exercism\csharp\generators\Program.cs:line 48
    at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
    at Generators.Program.Main(String[] args) in .\exercism\csharp\generators\Program.cs:line 18

Here is the list of the generators to check:

    .\exercism\csharp\generators\Exercises\Allergies.cs(17):              canonicalDataCase.SetConstructorInputParameters("score");
    .\exercism\csharp\generators\Exercises\Anagram.cs(13):                canonicalDataCase.SetConstructorInputParameters("subject");
    .\exercism\csharp\generators\Exercises\BinarySearch.cs(12):           canonicalDataCase.SetConstructorInputParameters("array");
    .\exercism\csharp\generators\Exercises\ComplexNumbers.cs(33):         canonicalDataCase.SetConstructorInputParameters("real", "imaginary");
    .\exercism\csharp\generators\Exercises\Connect.cs(13):                canonicalDataCase.SetConstructorInputParameters("board");
    .\exercism\csharp\generators\Exercises\KindergartenGarden.cs(19):     canonicalDataCase.SetConstructorInputParameters("diagram", "students");
    .\exercism\csharp\generators\Exercises\KindergartenGarden.cs(21):     canonicalDataCase.SetConstructorInputParameters("diagram");
    .\exercism\csharp\generators\Exercises\Matrix.cs(11):                 canonicalDataCase.SetConstructorInputParameters("string");
    .\exercism\csharp\generators\Exercises\NucleotideCount.cs(17):        canonicalDataCase.SetConstructorInputParameters("strand");
    .\exercism\csharp\generators\Exercises\RailFenceCipher.cs(13):        canonicalDataCase.SetConstructorInputParameters("rails");\
    .\exercism\csharp\generators\Exercises\SaddlePoints.cs(16):           canonicalDataCase.SetConstructorInputParameters("input");
    .\exercism\csharp\generators\Exercises\SpaceAge.cs(13):               canonicalDataCase.SetConstructorInputParameters("seconds");
    .\exercism\csharp\generators\Exercises\TwoBucket.cs(13):              canonicalDataCase.SetConstructorInputParameters("bucket_one", "bucket_two", "start_bucket");

Correct usage of .SetConstructorInputParameters can be found in [Meetup.cs](https://github.com/exercism/csharp/blob/master/generators/Exercises/Meetup.cs)

**Comment by ErikSchierboom** [comment]
Being worked on as part of #568.
