### ISSUE TITLE
FileNotFoundException when running generators

### ISSUE THREAD

**Issue by robkeim** [exercism/csharp#723]
I'm running into the following exception when trying to run the generators:
```
System.IO.FileNotFoundException: Could not find file 'C:\[...]\generators\bin\Debug\config.json'.File name: 'C:\[...]\generators\bin\Debug\config.json'
    at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
    at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize)
    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks)
    at System.IO.File.InternalReadAllText(String path, Encoding encoding)
    at System.IO.File.ReadAllText(String path)
    at Exercism.CSharp.Input.TrackConfigFile.GetExercises() in C:\[...]\generators\Input\TrackConfigFile.cs:line 15
    at Exercism.CSharp.Exercises.ExerciseCollection.GetExercises()+MoveNext() in C:\[...]\generators\Exercises\ExerciseCollection.cs:line 36
    at Exercism.CSharp.Program.RegenerateTestClasses(Options options, String[] args) in C:\[...]\generators\Program.cs:line 50
    at Exercism.CSharp.Program.<>c__DisplayClass0_0.<Main>b__0(Options options) in C:\[...]\generators\Program.cs:line 21
    at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
    at Exercism.CSharp.Program.Main(String[] args) in C:\[...]\generators\Program.cs:line 20
```

`[...]` is a replacement for the path to the repo on my local drive.

I'm attempting to run the generators in VS 2017 on Windows.

**Comment by ErikSchierboom** [comment]
> I'm attempting to run the generators in VS 2017 on Windows.

Ah, I think I know what the issue is. In this case, the working directory is set to the root directory, and not to the generators directory. It might be good to fix this, such that the `config.json` file is also copied to the directory in which the artifacts are built.

**Comment by robkeim** [comment]
That's definitely the issue but I don't think the fix is that straightforward unfortunately :(

If we update `config.json` to copy it to the build output it will fix the that issue which is this line:
https://github.com/exercism/csharp/blob/5a853404da1409ff9fc7a314c801d97ba8d18d55/generators/Input/TrackConfigFile.cs#L11

However, we still have the part where the exercise test class name lives so we need to get a reference to the original root somehow:
https://github.com/exercism/csharp/blob/5a853404da1409ff9fc7a314c801d97ba8d18d55/generators/Helpers/FilePathHelper.cs#L7

**Comment by robkeim** [comment]
I can set the working directory manually in the debugger but haven't figured out a way to commit that into the csproj yet:
https://codeyarns.com/2013/12/30/how-to-change-working-directory-in-visual-studio

**Comment by robkeim** [comment]
The issue is being discussed in more detail here:
https://github.com/dotnet/project-system/issues/3619

**Comment by ErikSchierboom** [comment]
Ah good find! I guess this we can keep this issue open until the reference issue is fixed.

**Comment by teb0ho** [comment]
Seems like this exercise comes pre-loaded with a working solution when you clone it.
